global:
  checkNewVersion: true
  sendAnonymousUsage: false

log:
  level: INFO
  format: common

api:
  dashboard: true
  insecure: true

entryPoints:
  web:
    address: ":80"
  websecure:
    address: ":443"

# Usunięto przekierowanie HTTP->HTTPS, które powodowało problemy
# Usunięto resolver cloudflare, który wymagał zmiennych środowiskowych

providers:
  docker:
    endpoint: "unix:///var/run/docker.sock"
    exposedByDefault: false
    network: deploy-network
  file:
    directory: "/etc/traefik/dynamic"
    watch: true

accessLog:
  filePath: "/var/log/traefik/access.log"
  format: json
  bufferingSize: 100

# Usunięto sekcję metrics, która powodowała błędy
